service: securus-dynamodb

resources:
  Description: DynamoDB Table for Securus GraphQL API
  Resources:
    DDBTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: ${self:custom.${self:provider.stage}.deletionPolicy}
      Properties:
        TableName: ${self:service}-${self:provider.stage}-0.1.0
        KeySchema:
          - AttributeName: pk
            KeyType: HASH
          - AttributeName: sk
            KeyType: RANGE
        AttributeDefinitions:
          - AttributeName: pk
            AttributeType: S
          - AttributeName: sk
            AttributeType: S
        Tags:
          - Key: project
            Value: securus
          - Key: service
            Value: ${self:service}
        BillingMode: PAY_PER_REQUEST
  Outputs:
    DDBTable:
      Value:
        Ref: DDBTable
      Export:
        Name: DDBTableSecurus
    DDBTableArn:
      Value:
        Fn::GetAtt: ['DDBTable', 'Arn']
      Export:
        Name: DDBTableArnSecurus
    Region:
      Value: ${self:provider.region}

provider:
  name: aws
  region: ap-southeast-1
  stage: dev
  lambdaHashingVersion: '20201221'
  tags:
    project: securus
    service: ${self:service}
    component: cloudformation

custom:
  dev:
    deletionPolicy: Delete
  prod:
    deletionPolicy: Retain
  output:
    file: ./stack.${self:provider.stage}.json

plugins:
  - serverless-stack-output

frameworkVersion: '>=2.21.0'
